# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#
# Copyright (C) 2019 P3TERX
#
# Copyright (C) 2020 KFERMercer
#
name: OpenWrt-CI-test
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Clone source code
      run: |
        git clone $REPO_URL -b $REPO_BRANCH

    - name: Generate Release Tag
      id: tag
      run: |
        echo "release_tag=OpenWrt_X86_64_$(date +"%Y-%m-%d_%H_%M")" >> $GITHUB_OUTPUT
        
        echo "## 更新内容" >> release.txt
        echo "Openwrt 最新提交内容： " >> release.txt     
        cd lede
        git log --oneline -n 10 >> release.txt
        cat release.txt
        ls -al
        echo "## 结束"
          
        touch release.txt
        echo "status=success" >> $GITHUB_OUTPUT
                
     
